"""Use cases (documents, ingestion, question answering) and their contracts: ports, domain errors, user keys."""
from vectorless_rag.operations.documents import DocumentLibrary, Upload
from vectorless_rag.operations.errors import (
    AnswerIncomplete,
    DocumentNotFound,
    DocumentNotReady,
    DuplicateDocument,
    FileTooLarge,
    ScannedDocument,
    TooManyPages,
    UnsupportedFile,
    VectorlessRagError,
    ViewPagesRejected,
)
from vectorless_rag.operations.ingestion import DocumentIngestion, IngestionRules, requeue_interrupted
from vectorless_rag.operations.ports import (
    AnswerAgent,
    CountPages,
    DetectFigurePages,
    DocumentRepository,
    FigureDescriber,
    FigureRepository,
    FileStore,
    PageRenderer,
    PageViewer,
    ReadPageTexts,
    UserIndex,
    UserIndexProvider,
    UserLocks,
    WriteInvisibleNotes,
)
from vectorless_rag.operations.query import QuestionAnswering, page_ranges, parse_pages
from vectorless_rag.operations.users import checked_user_key, user_key_for

__all__ = [
    "AnswerAgent",
    "AnswerIncomplete",
    "CountPages",
    "DetectFigurePages",
    "DocumentIngestion",
    "DocumentLibrary",
    "DocumentNotFound",
    "DocumentNotReady",
    "DocumentRepository",
    "DuplicateDocument",
    "FigureDescriber",
    "FigureRepository",
    "FileStore",
    "FileTooLarge",
    "IngestionRules",
    "PageRenderer",
    "PageViewer",
    "QuestionAnswering",
    "ReadPageTexts",
    "ScannedDocument",
    "TooManyPages",
    "UnsupportedFile",
    "Upload",
    "UserIndex",
    "UserIndexProvider",
    "UserLocks",
    "VectorlessRagError",
    "ViewPagesRejected",
    "WriteInvisibleNotes",
    "checked_user_key",
    "page_ranges",
    "parse_pages",
    "requeue_interrupted",
    "user_key_for",
]
