"""Use cases (ingestion) and their contracts: the ports adapters implement, domain errors, user keys."""
from vectorless_rag.operations.errors import (
    DocumentNotFound,
    DocumentNotReady,
    DuplicateDocument,
    FileTooLarge,
    ScannedDocument,
    TooManyPages,
    UnsupportedFile,
    VectorlessRagError,
    ViewPagesRejected,
)
from vectorless_rag.operations.ingestion import DocumentIngestion, IngestionRules, requeue_interrupted
from vectorless_rag.operations.ports import (
    AnswerAgent,
    DetectFigurePages,
    DocumentRepository,
    FigureDescriber,
    FigureRepository,
    FileStore,
    PageRenderer,
    PageViewer,
    ReadPageTexts,
    UserIndex,
    UserIndexProvider,
    UserLocks,
    WriteInvisibleNotes,
)
from vectorless_rag.operations.users import user_key_for

__all__ = [
    "AnswerAgent",
    "DetectFigurePages",
    "DocumentIngestion",
    "DocumentNotFound",
    "DocumentNotReady",
    "DocumentRepository",
    "DuplicateDocument",
    "FigureDescriber",
    "FigureRepository",
    "FileStore",
    "FileTooLarge",
    "IngestionRules",
    "PageRenderer",
    "PageViewer",
    "ReadPageTexts",
    "ScannedDocument",
    "TooManyPages",
    "UnsupportedFile",
    "UserIndex",
    "UserIndexProvider",
    "UserLocks",
    "VectorlessRagError",
    "ViewPagesRejected",
    "WriteInvisibleNotes",
    "requeue_interrupted",
    "user_key_for",
]
